name: Build and Publish Vue.js Docker image to GHCR

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-push-frontend.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-push-frontend.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jarrobots/pri_frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jarrobots
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Vue.js Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend     # adjust if needed
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/jarrobots/pri_frontend:latest
            ghcr.io/jarrobots/pri_frontend:${{ github.sha }}
